// <auto-generated />
namespace CemeterySystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FamilyMember_With_AspNetUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FamilyMember_With_AspNetUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201803171635024_FamilyMember_With_AspNetUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
