// <auto-generated />
namespace CemeterySystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DB_VERSION_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB_VERSION_1));
        
        string IMigrationMetadata.Id
        {
            get { return "201803140938390_DB_VERSION_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
